{
  "hash": "d258870184c43c8e5ffc4d807fae744b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Yiting Zhong\"\ndate: Feb 22,2026\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n  \n---\n\n## Assignment Overview\n\n**Learning Objectives:**\n- Apply spatial operations to answer policy-relevant research questions\n- Integrate census demographic data with spatial analysis\n- Create publication-quality visualizations and maps\n- Work with spatial data from multiple sources\n- Communicate findings effectively for policy audiences\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n**Your Task:**\n\n::: {.cell}\n\n:::\n\n\n**Questions to answer:**\n\n- How many hospitals are in your dataset?\n\n  223\n\n\n- How many census tracts?\n\n  3445\n\n\n- What coordinate reference system is each dataset in?\n\n  pa_hospitals=WGS 84 ,\"EPSG\",4326\n  pa_tracts=NAD83,\"EPSG\",4269\n  pa_counties=WGS 84,\"EPSG\",3857\n  \n---\n\n#### Step 2: Get Demographic Data \n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\nlibrary(tidycensus)\nvars <- c(\n  total_pop = \"B01001_001\",     \n  med_income = \"B19013_001\",    \n  m65_66 = \"B01001_020\", m67_69 = \"B01001_021\", m70_74 = \"B01001_022\", \n  m75_79 = \"B01001_023\", m80_84 = \"B01001_024\", m85_plus = \"B01001_025\",\n  f65_66 = \"B01001_044\", f67_69 = \"B01001_045\", f70_74 = \"B01001_046\", \n  f75_79 = \"B01001_047\", f80_84 = \"B01001_048\", f85_plus = \"B01001_049\"\n)\npa_census_data <- get_acs(\n  geography = \"tract\",\n  variables = vars,\n  state = \"PA\",\n  year = 2022, \n  output = \"wide\" \n)\npa_demographics <- pa_census_data %>%\n  mutate(\n    elderly_pop = rowSums(select(., m65_66E:f85_plusE)),\n    elderly_pct = (elderly_pop / total_popE) * 100\n  ) %>%\n  rename(\n    total_population = total_popE,\n    median_income = med_incomeE\n  ) %>%\n  select(GEOID, NAME, total_population, median_income, elderly_pop, elderly_pct)\n\n# Join to tract boundaries\npa_tracts_with_data <- pa_tracts %>%\n  left_join(pa_demographics, by = \"GEOID\")\n```\n:::\n\n\n**Questions to answer:**\n\n- What year of ACS data are you using?\n\n  2022\n\n- How many tracts have missing income data?\n\n  62\n\n- What is the median income across all PA census tracts?\n\n  70188\n\n\n---\n\n#### Step 3: Define Vulnerable Populations \n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\npa_valid_data <- pa_tracts_with_data %>%\n  filter(!is.na(median_income)) %>%\n  filter(total_population > 0)\n\nincome_limit <- 55924\nelderly_limit<- 37.7\n\n\npa_vulnerable_populations <- pa_valid_data %>%\n  mutate(\n    is_vulnerable = ifelse(\n      !is.na(median_income) & \n      median_income <= income_limit & \n      elderly_pct >= elderly_limit, \n      TRUE, \n      FALSE\n    )\n  ) %>%\n  filter(is_vulnerable == TRUE)\n```\n:::\n\n\n**Questions to answer:**\n\n- What income threshold did you choose and why?\n\n  55924, I use the 75% quantile. quantile(pa_valid_data$elderly_pct,0.25, na.rm = TRUE)\n\n- What elderly population threshold did you choose and why?\n\n  37.7, I found that the 75th percentile is approximately 25%. This means this threshold helps me identify the top 25% of communities with the highest aging levels across the state. quantile(pa_valid_data$elderly_pct,0.75, na.rm = TRUE)\n\n- How many tracts meet your vulnerability criteria?\n  \n  209\n\n- What percentage of PA census tracts are considered vulnerable by your definition?\n\n  209/3445=6.07%\n  \n---\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\npa_vulnerable_projected <- st_transform(pa_vulnerable_populations, 2272)\npa_hospitals_projected <- st_transform(pa_hospitals, 2272)\n\nvulnerable_centroids <- st_centroid(pa_vulnerable_projected)\n\ndistance<- st_distance(vulnerable_centroids,pa_hospitals_projected)\n\npa_vulnerable_projected$dist_to_hospital_miles <- as.numeric(apply(distance, 1, min)) / 5280\n```\n:::\n\n\n**Questions to answer:**\n\n- What is the average distance to the nearest hospital for vulnerable tracts?\n\n  3.538635\n\n- What is the maximum distance?\n\n  19.15822\n\n- How many vulnerable tracts are more than 15 miles from the nearest hospital?\n  \n  7\n  \n---\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\npa_vulnerable_projected<- pa_vulnerable_projected %>%\n  mutate(is_underserved = dist_to_hospital_miles > 15)\n```\n:::\n\n\n**Questions to answer:**\n\n- How many tracts are underserved?\n7\n\n- What percentage of vulnerable tracts are underserved?\n7/209=3.34%\n\n- Does this surprise you? Why or why not?\nYes, because there are almost 20,000 of population have to go to hospital that is more than 15 miles away.\n---\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join tracts to counties\npa_counties_projected <- st_transform(pa_counties, 2272)\nvulnerable_with_county <- st_join(pa_vulnerable_projected, pa_counties_projected)\n\n# Aggregate statistics by county\ncounty_summary <- vulnerable_with_county %>%\n  group_by(NAMELSADCO) %>%\n  summarize(\n    num_vulnerable_tracts=n(),\n    num_underserved_tracts = sum(is_underserved),\n    avg_distance=mean(dist_to_hospital_miles),\n    total_vulnerable_population=sum(total_population,na.rm = TRUE))%>%\n      mutate(\n        pct_vul_tracts_underserved=((num_underserved_tracts / num_vulnerable_tracts)*100)\n      )\n```\n:::\n\n\n**Questions to answer:**\n\n- Which 5 counties have the highest percentage of underserved vulnerable tracts?\n\n  Forest County, \tJuniata County, Monroe County, Sullivan County,Dauphin County\n\n- Which counties have the most vulnerable people living far from hospitals?\n  \n  Forest County\n\n- Are there any patterns in where underserved counties are located?\n  \n  Underserved counties are primarily concentrated in the rural, mountainous central and northern regions of PA, where low population density leads to sparse hospital coverage.\n\n---\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(knitr)\n# Create and format priority counties table\ntop_10_counties<-county_summary%>%\n  st_drop_geometry()%>%\n  arrange(desc(pct_vul_tracts_underserved))%>%\n  head(10)%>%\n  mutate(\n    avg_distance = round(avg_distance, 1)\n  )\n  \n\ntop_10_counties %>%\n  kable(\n    col.names = c(\"County Name\", \"Vulnerable Tracts\", \"Underserved Tracts\", \n                  \"Avg. Distance (mi)\", \"Total Vulnerable Pop\", \"% Underserved\"),\n    caption = \"Top 10 Pennsylvania Counties Prioritized for Healthcare Investment\",\n    align = \"lccccc\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 10 Pennsylvania Counties Prioritized for Healthcare Investment\n\n|County Name       | Vulnerable Tracts | Underserved Tracts | Avg. Distance (mi) | Total Vulnerable Pop | % Underserved |\n|:-----------------|:-----------------:|:------------------:|:------------------:|:--------------------:|:-------------:|\n|Forest County     |         4         |         4          |        18.1        |        10804         |      100      |\n|Juniata County    |         5         |         5          |        15.9        |         8910         |      100      |\n|Monroe County     |         1         |         1          |        17.7        |         1299         |      100      |\n|Sullivan County   |         4         |         4          |        16.9        |         3672         |      100      |\n|Dauphin County    |         4         |         3          |        14.6        |        16446         |      75       |\n|Bradford County   |         2         |         1          |        9.3         |         8736         |      50       |\n|Clearfield County |         4         |         2          |        9.0         |        17256         |      50       |\n|Allegheny County  |        35         |         0          |        2.3         |        78986         |       0       |\n|Armstrong County  |         1         |         0          |        3.1         |         2850         |       0       |\n|Beaver County     |         7         |         0          |        3.1         |        13889         |       0       |\n\n\n:::\n:::\n\n---\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create county-level access map\nlibrary(sf)\nlibrary(ggplot2)\nlibrary(tidyverse)\n\ncounty_summary_clean <- county_summary %>%\n  st_drop_geometry() %>%\n  mutate(\n    join_name = toupper(str_remove_all(NAMELSADCO, \"(?i)\\\\s*COUNTY\"))\n  )\nmap1_data <- pa_counties_projected %>%\n  mutate(\n    join_name =COUNTY_NAM\n  ) %>%\n  left_join(county_summary_clean, by = \"join_name\")\n\nggplot() +\n  geom_sf(data = map1_data, aes(fill = pct_vul_tracts_underserved), color = \"white\", size = 0.3) +\n  geom_sf(data = pa_hospitals_projected, color = \"#e41a1c\", size = 1, alpha = 1) +\n  scale_fill_viridis_c(\n    name = \"% Underserved\",\n    option = \"plasma\", \n    na.value = \"grey85\",\n    labels = scales::label_percent(scale = 1)\n  ) +\n  labs(\n    title = \"Healthcare Access Challenges by County\",\n    subtitle = \"Percentage of vulnerable census tracts > 15 miles from a hospital\",\n    caption = \"Data Source: 2022 ACS & PA Open Data\"\n  ) +\n  \n  theme_void() +\n  theme(\n    legend.position = \"right\",\n    plot.title = element_text(face = \"bold\", size = 16),\n    plot.subtitle = element_text(size = 11, color = \"grey30\")\n  )\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed tract-level map\nunderserved_tracts<-pa_vulnerable_projected%>%\n  filter(is_underserved==TRUE)\n\nggplot()+\n  geom_sf(data=pa_counties_projected,fill=\"grey85\",color=\"grey95\",size=0.5)+\n    geom_sf(data = underserved_tracts,fill=\"#d95f02\", color = NA)+\n    geom_sf(data = pa_hospitals_projected,color=\"red\",size=1)+\nlabs(\n  title = \"Healthcare Deserts in Pennsylvania\",\n  subtitle = \"Vulnerable census tracts located > 15 miles from the nearest hospital (highlighted in orange)\",\n caption = \"Data Source: 2022 ACS & PA Open Data\"\n)+\n  theme_void()+\n  theme(\n    plot.title = element_text(face = \"bold\", size = 16),\n    plot.subtitle = element_text(size = 11, color = \"grey30\"),\n    plot.margin = margin(10, 10, 10, 10)\n  )\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n---\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\nggplot(data = pa_vulnerable_projected, aes(x = dist_to_hospital_miles)) +\n  geom_histogram(binwidth = 2, fill = \"#4575b4\", color = \"white\", alpha = 0.8) +\n  geom_vline(xintercept = 15, color = \"#d73027\", linetype = \"dashed\", size = 1.2) +\n  annotate(\"text\", x = 15.5, y = Inf, label = \"15-mile Threshold\\n(Underserved)\", \n           vjust = 1.5, hjust = 0, color = \"#d73027\", fontface = \"bold\", size = 4) +\n  labs(\n    title = \"How Far Are Vulnerable Communities from Hospitals?\",\n    subtitle = \"Distribution of distances to the nearest hospital for vulnerable census tracts in PA\",\n    x = \"Distance to Nearest Hospital (Miles)\",\n    y = \"Number of Census Tracts\",\n    caption = \"Data Source: 2022 ACS & PA Open Data\"\n  ) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 15),\n    plot.subtitle = element_text(size = 11, color = \"grey30\"),\n    axis.title.x = element_text(margin = margin(t = 10), face = \"bold\"),\n    axis.title.y = element_text(margin = margin(r = 10), face = \"bold\"),\n    panel.grid.minor = element_blank() \n  )\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n---\n\n## Part 3: Bring Your Own Data Analysis \n\n#### Environmental Justice\n\n**Green Space Equity** \n- **Data:** Parks, Street Trees, Census tracts (race/income demographics)\n- **Question:** \"Do low-income and minority neighborhoods have equitable access to green space?\"\n\n- **Operations:** Buffer parks (10-minute walk = 0.5 mile), calculate tree canopy or park acreage per capita, compare by demographics\n- **Policy relevance:** Climate resilience, environmental justice, urban forestry investment\n\n### Data Sources\n\n**OpenDataPhilly:** https://opendataphilly.org/datasets/\n\n\n### Your Analysis\n\n**Your Task:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load your additional dataset\nlibrary(sf)\nlibrary(tidyverse)\nphily_Recreation<- st_read(\"C:/Users/yzhon/OneDrive - PennO365/Penn-Spring 2026/CPLN 592/cpln-5920-sp26-student-portfolio-template/Labs/Lab_2/PPR_Properties.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `PPR_Properties' from data source \n  `C:\\Users\\yzhon\\OneDrive - PennO365\\Penn-Spring 2026\\CPLN 592\\cpln-5920-sp26-student-portfolio-template\\Labs\\Lab_2\\PPR_Properties.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 504 features and 25 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -75.28353 ymin: 39.87117 xmax: -74.95865 ymax: 40.13186\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(st_crs(phily_Recreation)$epsg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4326\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(phily_Recreation)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n public_name        parent_name           nested          official_name     \n Length:504         Length:504         Length:504         Length:504        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n    label              alias           dpp_asset_id       address_911       \n Length:504         Length:504         Length:504         Length:504        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n   zip_code         address_brt        alias_address         acreage         \n Length:504         Length:504         Length:504         Min.   :1.925e-02  \n Class :character   Class :character   Class :character   1st Qu.:8.849e-01  \n Mode  :character   Mode  :character   Mode  :character   Median :3.563e+00  \n                                                          Mean   :2.007e+01  \n                                                          3rd Qu.:8.215e+00  \n                                                          Max.   :1.683e+03  \n property_classification   ppr_use          ppr_prog_district \n Length:504              Length:504         Length:504        \n Class :character        Class :character   Class :character  \n Mode  :character        Mode  :character   Mode  :character  \n                                                              \n                                                              \n                                                              \n ppr_ops_district   council_district   police_district    city_scale_maps   \n Length:504         Length:504         Length:504         Length:504        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n local_scale_maps   program_sites        comments            objectid    \n Length:504         Length:504         Length:504         Min.   :  1.0  \n Class :character   Class :character   Class :character   1st Qu.:126.8  \n Mode  :character   Mode  :character   Mode  :character   Median :252.5  \n                                                          Mean   :252.5  \n                                                          3rd Qu.:378.2  \n                                                          Max.   :504.0  \n  Shape__Area        Shape__Length               geometry  \n Min.   :1.328e+02   Min.   :   57.99   MULTIPOLYGON :504  \n 1st Qu.:6.102e+03   1st Qu.:  361.78   epsg:4326    :  0  \n Median :2.467e+04   Median :  715.52   +proj=long...:  0  \n Mean   :1.387e+05   Mean   : 1721.22                      \n 3rd Qu.:5.667e+04   3rd Qu.: 1228.31                      \n Max.   :1.164e+07   Max.   :91233.29                      \n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n\n- What dataset did you choose and why?\n\n  I used PPR_Properties.geojson,I selected this to analyze green space equity (Option C), as access to public parks is a crucial indicator of public health and urban environmental quality.\n\n- What is the data source and date?\n  \n  The data is sourced from OpenDataPhilly, not sure the exact date.\n\n- How many features does it contain?\n\n  504\n\n- What CRS is it in? Did you need to transform it?\n  \n  4326,yes, I change to 2272(PA south).\n  \n---\n\n2. **Pose a research question**\n\nDo vulnerable census tracts in Philadelphia have equitable walking access to public parks and green spaces?\n\n---\n\n3. **Conduct spatial analysis**\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your spatial analysis\nphily_Recreation_projected<- st_transform(phily_Recreation,2272)\n\nphilly_tracts<- pa_tracts_with_data %>%\n  filter(str_detect(NAMELSADCO,\"Philadelphia County\"))%>%\n  st_transform(2272)\n\nphilly_centroids<- st_centroid(philly_tracts)\n\nparks_unioned <- st_union(phily_Recreation_projected)\n\npark_to_tracts <- st_distance(philly_centroids, parks_unioned)\n\nphilly_tracts$dist_to_park_miles <- as.numeric(park_to_tracts) / 5280\n\nggplot() +\n  geom_sf(data = philly_tracts, aes(fill = dist_to_park_miles), color = NA) +\n  scale_fill_viridis_c(\n    name = \"Miles to Park\", \n    option = \"mako\", \n    direction = -1  \n  ) +\n  labs(\n    title = \"Park Accessibility in Philadelphia\",\n    subtitle = \"Distance from neighborhood centroids to the nearest recreation property\",\n    caption = \"Data: OpenDataPhilly & ACS\"\n  ) +\n  theme_void() +\n  theme(plot.title = element_text(face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# 确保加载了表格所需的包\nlibrary(knitr)\nlibrary(dplyr)\n\npark_access_summary <- philly_tracts %>%\n  st_drop_geometry() %>% \n  mutate(\n    access_level = case_when(\n      dist_to_park_miles <= 0.5 ~ \"0 - 0.5 miles (Excellent Walkability)\",\n      dist_to_park_miles > 0.5 & dist_to_park_miles <= 1.0 ~ \"0.5 - 1.0 miles (Good)\",\n      dist_to_park_miles > 1.0 & dist_to_park_miles <= 2.0 ~ \"1.0 - 2.0 miles (Fair)\",\n      dist_to_park_miles > 2.0 ~ \"> 2.0 miles (Park Desert)\",\n      TRUE ~ \"Unknown\"\n    )\n  ) %>%\n  group_by(access_level) %>%\n  summarize(\n    number_of_tracts = n()\n  ) %>%\n  mutate(\n    percentage = paste0(round((number_of_tracts / sum(number_of_tracts)) * 100, 1), \"%\")\n  )\npark_access_summary %>%\n  kable(\n    col.names = c(\"Distance to Nearest Park\", \"Number of Tracts\", \"Percentage (%)\"),\n    caption = \"Distribution of Park Accessibility across Philadelphia Census Tracts\",\n    align = \"lcc\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Distribution of Park Accessibility across Philadelphia Census Tracts\n\n|Distance to Nearest Park              | Number of Tracts | Percentage (%) |\n|:-------------------------------------|:----------------:|:--------------:|\n|0 - 0.5 miles (Excellent Walkability) |       390        |     95.6%      |\n|0.5 - 1.0 miles (Good)                |        17        |      4.2%      |\n|1.0 - 2.0 miles (Fair)                |        1         |      0.2%      |\n\n\n:::\n:::\n\n\n**Your interpretation:**\n\nBased on the spatial analysis, basic park accessibility in Philadelphia is exceptionally high. The summary statistics reveal that 95.6% of census tracts enjoy \"Excellent Walkability\", being located within a 0.5-mile radius of a recreation property.However, the map highlights specific spatial gaps primarily in the extreme southern and far northeastern edges of the city. From a planning perspective, these are largely driven by distinct land-use patterns: the deep south is dominated by industrial zones and the Philadelphia International Airport (where residential population is minimal), while the Far Northeast features a more suburban, auto-oriented built environment where residents often have access to private yards, reducing the historical demand for dense public pocket parks. Overall, the city demonstrates strong spatial equity in baseline park access.\n\n\n## Finally - A few comments about your incorporation of feedback!\n\nI clean up the template,and use echo:false to hide all the library set up code.I avoid using print() and head()this time.\n\n---\n\n",
    "supporting": [
      "lab2_template_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}