<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yiting Zhong">
<meta name="dcterms.date" content="2026-02-10">

<title>Lab 1: Census Data Quality for Policy Decisions – Yiting Zhong - MUSA 5080 Portfolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-e31584831b205ffbb2d98406f31c2a5b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Yiting Zhong - MUSA 5080 Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Labs"> 
<span class="menu-text">Lab 1</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#assignment-overview" id="toc-assignment-overview" class="nav-link active" data-scroll-target="#assignment-overview">Assignment Overview</a>
  <ul class="collapse">
  <li><a href="#scenario" id="toc-scenario" class="nav-link" data-scroll-target="#scenario">Scenario</a></li>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#submission-instructions" id="toc-submission-instructions" class="nav-link" data-scroll-target="#submission-instructions">Submission Instructions</a></li>
  </ul></li>
  <li><a href="#part-1-portfolio-integration" id="toc-part-1-portfolio-integration" class="nav-link" data-scroll-target="#part-1-portfolio-integration">Part 1: Portfolio Integration</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#part-2-county-level-resource-assessment" id="toc-part-2-county-level-resource-assessment" class="nav-link" data-scroll-target="#part-2-county-level-resource-assessment">Part 2: County-Level Resource Assessment</a>
  <ul class="collapse">
  <li><a href="#data-retrieval" id="toc-data-retrieval" class="nav-link" data-scroll-target="#data-retrieval">2.1 Data Retrieval</a></li>
  <li><a href="#data-quality-assessment" id="toc-data-quality-assessment" class="nav-link" data-scroll-target="#data-quality-assessment">2.2 Data Quality Assessment</a></li>
  <li><a href="#high-uncertainty-counties" id="toc-high-uncertainty-counties" class="nav-link" data-scroll-target="#high-uncertainty-counties">2.3 High Uncertainty Counties</a></li>
  </ul></li>
  <li><a href="#part-3-neighborhood-level-analysis" id="toc-part-3-neighborhood-level-analysis" class="nav-link" data-scroll-target="#part-3-neighborhood-level-analysis">Part 3: Neighborhood-Level Analysis</a>
  <ul class="collapse">
  <li><a href="#focus-area-selection" id="toc-focus-area-selection" class="nav-link" data-scroll-target="#focus-area-selection">3.1 Focus Area Selection</a></li>
  <li><a href="#tract-level-demographics" id="toc-tract-level-demographics" class="nav-link" data-scroll-target="#tract-level-demographics">3.2 Tract-Level Demographics</a></li>
  <li><a href="#demographic-analysis" id="toc-demographic-analysis" class="nav-link" data-scroll-target="#demographic-analysis">3.3 Demographic Analysis</a></li>
  </ul></li>
  <li><a href="#part-4-comprehensive-data-quality-evaluation" id="toc-part-4-comprehensive-data-quality-evaluation" class="nav-link" data-scroll-target="#part-4-comprehensive-data-quality-evaluation">Part 4: Comprehensive Data Quality Evaluation</a>
  <ul class="collapse">
  <li><a href="#moe-analysis-for-demographic-variables" id="toc-moe-analysis-for-demographic-variables" class="nav-link" data-scroll-target="#moe-analysis-for-demographic-variables">4.1 MOE Analysis for Demographic Variables</a></li>
  <li><a href="#pattern-analysis" id="toc-pattern-analysis" class="nav-link" data-scroll-target="#pattern-analysis">4.2 Pattern Analysis</a></li>
  </ul></li>
  <li><a href="#part-5-policy-recommendations" id="toc-part-5-policy-recommendations" class="nav-link" data-scroll-target="#part-5-policy-recommendations">Part 5: Policy Recommendations</a>
  <ul class="collapse">
  <li><a href="#analysis-integration-and-professional-summary" id="toc-analysis-integration-and-professional-summary" class="nav-link" data-scroll-target="#analysis-integration-and-professional-summary">5.1 Analysis Integration and Professional Summary</a></li>
  <li><a href="#specific-recommendations" id="toc-specific-recommendations" class="nav-link" data-scroll-target="#specific-recommendations">6.3 Specific Recommendations</a></li>
  <li><a href="#questions-for-further-investigation" id="toc-questions-for-further-investigation" class="nav-link" data-scroll-target="#questions-for-further-investigation">Questions for Further Investigation</a></li>
  <li><a href="#submission-checklist" id="toc-submission-checklist" class="nav-link" data-scroll-target="#submission-checklist">Submission Checklist</a></li>
  </ul></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lab 1: Census Data Quality for Policy Decisions</h1>
<p class="subtitle lead">Evaluating Data Reliability for Algorithmic Decision-Making</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Yiting Zhong </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 10, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="assignment-overview" class="level1">
<h1>Assignment Overview</h1>
<section id="scenario" class="level2">
<h2 class="anchored" data-anchor-id="scenario">Scenario</h2>
<p>You are a data analyst for the <strong>CA Department of Human Services</strong>. The department is considering implementing an algorithmic system to identify communities that should receive priority for social service funding and outreach programs. Your supervisor has asked you to evaluate the quality and reliability of available census data to inform this decision.</p>
<p>Drawing on our Week 2 discussion of algorithmic bias, you need to assess not just what the data shows, but how reliable it is and what communities might be affected by data quality issues.</p>
</section>
<section id="learning-objectives" class="level2">
<h2 class="anchored" data-anchor-id="learning-objectives">Learning Objectives</h2>
<ul>
<li>Apply dplyr functions to real census data for policy analysis</li>
<li>Evaluate data quality using margins of error</li>
<li>Connect technical analysis to algorithmic decision-making</li>
<li>Identify potential equity implications of data reliability issues</li>
<li>Create professional documentation for policy stakeholders</li>
</ul>
</section>
<section id="submission-instructions" class="level2">
<h2 class="anchored" data-anchor-id="submission-instructions">Submission Instructions</h2>
<p><strong>Submit by posting your updated portfolio link on Canvas.</strong> Your assignment should be accessible at <code>your-portfolio-url/labs/lab_1/</code></p>
<p>Make sure to update your <code>_quarto.yml</code> navigation to include this assignment under an “Labs” menu.</p>
</section>
</section>
<section id="part-1-portfolio-integration" class="level1">
<h1>Part 1: Portfolio Integration</h1>
<p>Create this assignment in your portfolio repository under an <code>labs/lab_1/</code> folder structure. Update your navigation menu to include:</p>
<pre><code>- text: Assignments
  menu:
    - href: labs/lab_1/your_file_name.qmd
      text: "Lab 1: Census Data Exploration"</code></pre>
<p>If there is a special character like a colon, you need use double quote mark so that the quarto can identify this as text</p>
</section>
<section id="setup" class="level1">
<h1>Setup</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required packages (hint: you need tidycensus, tidyverse, and knitr)</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidycensus)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Set your Census API key</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">census_api_key</span>(<span class="st">"577f52cafa8132078e715d2f9f7321573a862bd1"</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Choose your state for analysis - assign it to a variable called my_state</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>my_state<span class="ot">=</span><span class="st">"CA"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>State Selection:</strong> I have chosen <strong>CA</strong> for this analysis because: it has diverse culture.</p>
</section>
<section id="part-2-county-level-resource-assessment" class="level1">
<h1>Part 2: County-Level Resource Assessment</h1>
<section id="data-retrieval" class="level2">
<h2 class="anchored" data-anchor-id="data-retrieval">2.1 Data Retrieval</h2>
<p><strong>Your Task:</strong> Use <code>get_acs()</code> to retrieve county-level data for your chosen state.</p>
<p><strong>Requirements:</strong> - Geography: county level - Variables: median household income (B19013_001) and total population (B01003_001)<br>
- Year: 2022 - Survey: acs5 - Output format: wide</p>
<p><strong>Hint:</strong> Remember to give your variables descriptive names using the <code>variables = c(name = "code")</code> syntax.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Write your get_acs() code here</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>county_data <span class="ot">&lt;-</span> <span class="fu">get_acs</span>(</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">geography =</span> <span class="st">"county"</span>,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> <span class="fu">c</span>(</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">med_income =</span> <span class="st">"B19013_001"</span>,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_pop =</span> <span class="st">"B01003_001"</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">state =</span> my_state,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">year =</span> <span class="dv">2022</span>,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">survey =</span> <span class="st">"acs5"</span>,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">output =</span> <span class="st">"wide"</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean the county names to remove state name and "County" </span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use mutate() with str_remove()</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>county_data_clean <span class="ot">&lt;-</span> county_data <span class="sc">%&gt;%</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">NAME =</span> <span class="fu">str_remove</span>(NAME, <span class="st">"County, California"</span>))</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the first few rows</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(county_data_clean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  GEOID NAME         med_incomeE med_incomeM total_popE total_popM
  &lt;chr&gt; &lt;chr&gt;              &lt;dbl&gt;       &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
1 06001 "Alameda "        122488        1231    1663823         NA
2 06003 "Alpine "         101125       17442       1515        206
3 06005 "Amador "          74853        6048      40577         NA
4 06007 "Butte "           66085        2261     213605         NA
5 06009 "Calaveras "       77526        3875      45674         NA
6 06011 "Colusa "          69619        5745      21811         NA</code></pre>
</div>
</div>
</section>
<section id="data-quality-assessment" class="level2">
<h2 class="anchored" data-anchor-id="data-quality-assessment">2.2 Data Quality Assessment</h2>
<p><strong>Your Task:</strong> Calculate margin of error percentages and create reliability categories.</p>
<p><strong>Requirements:</strong> - Calculate MOE percentage: (margin of error / estimate) * 100 - Create reliability categories: - High Confidence: MOE &lt; 5% - Moderate Confidence: MOE 5-10%<br>
- Low Confidence: MOE &gt; 10% - Create a flag for unreliable estimates (MOE &gt; 10%)</p>
<p><strong>Hint:</strong> Use <code>mutate()</code> with <code>case_when()</code> for the categories.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate MOE percentage and reliability categories using mutate()</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>income_analysis <span class="ot">&lt;-</span> county_data_clean <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">moe_pct =</span> (med_incomeM <span class="sc">/</span> med_incomeE) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">reliability =</span> <span class="fu">case_when</span>(</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>      moe_pct <span class="sc">&lt;</span> <span class="dv">5</span> <span class="sc">~</span> <span class="st">"High Confidence"</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>      moe_pct <span class="sc">&lt;=</span> <span class="dv">10</span> <span class="sc">~</span> <span class="st">"Moderate Confidence"</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Low Confidence"</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">unreliable_flag =</span> <span class="fu">if_else</span>(moe_pct <span class="sc">&gt;</span> <span class="dv">10</span>, <span class="st">"Yes"</span>, <span class="st">"No"</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a summary showing count of counties in each reliability category</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>reliability_summary <span class="ot">&lt;-</span> income_analysis <span class="sc">%&gt;%</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(reliability) <span class="sc">%&gt;%</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">percentage =</span> (n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(reliability_summary, <span class="at">digits =</span> <span class="dv">1</span>, <span class="at">caption =</span> <span class="st">"Summary of Data Reliability by County"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Summary of Data Reliability by County</caption>
<thead>
<tr class="header">
<th style="text-align: left;">reliability</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">percentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">High Confidence</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">72.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">8.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">19.0</td>
</tr>
</tbody>
</table>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use count() and mutate() to add percentages</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="high-uncertainty-counties" class="level2">
<h2 class="anchored" data-anchor-id="high-uncertainty-counties">2.3 High Uncertainty Counties</h2>
<p><strong>Your Task:</strong> Identify the 5 counties with the highest MOE percentages.</p>
<p><strong>Requirements:</strong> - Sort by MOE percentage (highest first) - Select the top 5 counties - Display: county name, median income, margin of error, MOE percentage, reliability category - Format as a professional table using <code>kable()</code></p>
<p><strong>Hint:</strong> Use <code>arrange()</code>, <code>slice()</code>, and <code>select()</code> functions.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create table of top 5 counties by MOE percentage</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>high_uncertainty_top5 <span class="ot">&lt;-</span> income_analysis <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(moe_pct))<span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>)<span class="sc">%&gt;%</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    NAME,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    med_incomeE,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    med_incomeM,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    moe_pct,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    reliability</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Format as table with kable() - include appropriate column names and caption</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>high_uncertainty_top5, </span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"County Name"</span>, <span class="st">"Median Income (Estimate)"</span>, <span class="st">"Margin of Error"</span>, <span class="st">"MOE %"</span>, <span class="st">"Reliability"</span>),</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="at">digits =</span> <span class="dv">2</span>,</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a><span class="at">caption =</span> <span class="st">"Top 5 counties with the highest Uncertainty"</span></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 5 counties with the highest Uncertainty</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 33%">
<col style="width: 21%">
<col style="width: 8%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">County Name</th>
<th style="text-align: right;">Median Income (Estimate)</th>
<th style="text-align: right;">Margin of Error</th>
<th style="text-align: right;">MOE %</th>
<th style="text-align: left;">Reliability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mono</td>
<td style="text-align: right;">82038</td>
<td style="text-align: right;">15388</td>
<td style="text-align: right;">18.76</td>
<td style="text-align: left;">Low Confidence</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alpine</td>
<td style="text-align: right;">101125</td>
<td style="text-align: right;">17442</td>
<td style="text-align: right;">17.25</td>
<td style="text-align: left;">Low Confidence</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sierra</td>
<td style="text-align: right;">61108</td>
<td style="text-align: right;">9237</td>
<td style="text-align: right;">15.12</td>
<td style="text-align: left;">Low Confidence</td>
</tr>
<tr class="even">
<td style="text-align: left;">Trinity</td>
<td style="text-align: right;">47317</td>
<td style="text-align: right;">5890</td>
<td style="text-align: right;">12.45</td>
<td style="text-align: left;">Low Confidence</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Plumas</td>
<td style="text-align: right;">67885</td>
<td style="text-align: right;">7772</td>
<td style="text-align: right;">11.45</td>
<td style="text-align: left;">Low Confidence</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Data Quality Commentary:</strong></p>
<p>[Write 2-3 sentences explaining what these results mean for algorithmic decision-making. Consider: Which counties might be poorly served by algorithms that rely on this income data? What factors might contribute to higher uncertainty?]</p>
<p>“The high MOE percentages in rural counties like Mono and Alpine (both over 17%) indicate that small sample sizes in sparsely populated areas lead to significant data instability. If algorithmic systems treat these”Low Confidence” estimates as absolute facts, they risk misallocating social services and reinforcing geographic inequities against rural communities. Consequently, these communities may be poorly served by automated decisions that fail to account for the inherent statistical uncertainty in their income data.”</p>
</section>
</section>
<section id="part-3-neighborhood-level-analysis" class="level1">
<h1>Part 3: Neighborhood-Level Analysis</h1>
<section id="focus-area-selection" class="level2">
<h2 class="anchored" data-anchor-id="focus-area-selection">3.1 Focus Area Selection</h2>
<p><strong>Your Task:</strong> Select 2-3 counties from your reliability analysis for detailed tract-level study.</p>
<p><strong>Strategy:</strong> Choose counties that represent different reliability levels (e.g., 1 high confidence, 1 moderate, 1 low confidence) to compare how data quality varies.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use filter() to select 2-3 counties from your county_reliability data</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Store the selected counties in a variable called selected_counties</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>selected_counties<span class="ot">&lt;-</span> income_analysis<span class="sc">%&gt;%</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(reliability) <span class="sc">%&gt;%</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(NAME, GEOID, med_incomeE, moe_pct, reliability)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the selected counties with their key characteristics</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>selected_counties, </span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"County Name"</span>, <span class="st">"GEOID"</span>, <span class="st">"Median Income (Estimate)"</span>, <span class="st">"MOE %"</span>, <span class="st">"Reliability"</span>),</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a><span class="at">caption =</span> <span class="st">"Representative Counties Selected for Each Reliability Level"</span></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Representative Counties Selected for Each Reliability Level</caption>
<colgroup>
<col style="width: 17%">
<col style="width: 8%">
<col style="width: 35%">
<col style="width: 10%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">County Name</th>
<th style="text-align: left;">GEOID</th>
<th style="text-align: right;">Median Income (Estimate)</th>
<th style="text-align: right;">MOE %</th>
<th style="text-align: left;">Reliability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alameda</td>
<td style="text-align: left;">06001</td>
<td style="text-align: right;">122488</td>
<td style="text-align: right;">1.005</td>
<td style="text-align: left;">High Confidence</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alpine</td>
<td style="text-align: left;">06003</td>
<td style="text-align: right;">101125</td>
<td style="text-align: right;">17.248</td>
<td style="text-align: left;">Low Confidence</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Amador</td>
<td style="text-align: left;">06005</td>
<td style="text-align: right;">74853</td>
<td style="text-align: right;">8.080</td>
<td style="text-align: left;">Moderate Confidence</td>
</tr>
</tbody>
</table>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Show: county name, median income, MOE percentage, reliability category</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Comment on the output:</strong> [I selected “Alameda”, ““Amador”, and “Alpine” to represent High, Moderate, and Low Confidence levels respectively. ]</p>
</section>
<section id="tract-level-demographics" class="level2">
<h2 class="anchored" data-anchor-id="tract-level-demographics">3.2 Tract-Level Demographics</h2>
<p><strong>Your Task:</strong> Get demographic data for census tracts in your selected counties.</p>
<p><strong>Requirements:</strong> - Geography: tract level - Variables: white alone (B03002_003), Black/African American (B03002_004), Hispanic/Latino (B03002_012), total population (B03002_001) - Use the same state and year as before - Output format: wide - <strong>Challenge:</strong> You’ll need county codes, not names. Look at the GEOID patterns in your county data for hints.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define your race/ethnicity variables with descriptive names</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>race_var <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">total_pop=</span> <span class="st">"B03002_001"</span>,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">white_alone=</span><span class="st">"B03002_003"</span>,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">black=</span><span class="st">"B03002_004"</span>,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">hispanic_latino=</span><span class="st">"B03002_012"</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Use get_acs() to retrieve tract-level data</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>target_counties <span class="ot">&lt;-</span> <span class="fu">str_sub</span>(selected_counties<span class="sc">$</span>GEOID, <span class="dv">3</span>, <span class="dv">5</span>)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>tract_data<span class="ot">&lt;-</span><span class="fu">get_acs</span>(</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">geography =</span> <span class="st">"tract"</span>,</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> race_var,</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">state =</span> my_state,</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">county =</span> target_counties,</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">year =</span> <span class="dv">2022</span>,</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">survey =</span> <span class="st">"acs5"</span>,</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">output =</span> <span class="st">"wide"</span></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: You may need to specify county codes in the county parameter</span></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate percentage of each group using mutate()</span></span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>tract_demographics <span class="ot">&lt;-</span> tract_data <span class="sc">%&gt;%</span></span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_white=</span> (white_aloneE<span class="sc">/</span>total_popE)<span class="sc">*</span><span class="dv">100</span>,</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_black=</span>(blackE<span class="sc">/</span>total_popE)<span class="sc">*</span><span class="dv">100</span>,</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_h_l=</span>(hispanic_latinoE<span class="sc">/</span>total_popE)<span class="sc">*</span><span class="dv">100</span>,</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">county_name =</span> <span class="fu">str_extract</span>(NAME, <span class="st">"(?&lt;=; ).*(?= County;)"</span>),</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">tract_name =</span> <span class="fu">str_extract</span>(NAME, <span class="st">"^[^,]*"</span></span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Create percentages for white, Black, and Hispanic populations</span></span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Add readable tract and county name columns using str_extract() or similar</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="demographic-analysis" class="level2">
<h2 class="anchored" data-anchor-id="demographic-analysis">3.3 Demographic Analysis</h2>
<p><strong>Your Task:</strong> Analyze the demographic patterns in your selected areas.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the tract with the highest percentage of Hispanic/Latino residents</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use arrange() and slice() to get the top tract</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>highest_h_l <span class="ot">&lt;-</span> tract_demographics <span class="sc">%&gt;%</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(pct_h_l)) <span class="sc">%&gt;%</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(NAME,pct_h_l, total_popE )</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate average demographics by county using group_by() and summarize()</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>average_demographics_couty <span class="ot">&lt;-</span> tract_demographics <span class="sc">%&gt;%</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(county_name) <span class="sc">%&gt;%</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">tract_count=</span> <span class="fu">n</span>(),</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_white=</span><span class="fu">mean</span>(pct_white, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_black=</span><span class="fu">mean</span>(pct_black, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_h_l=</span><span class="fu">mean</span>( pct_h_l, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Show: number of tracts, average percentage for each racial/ethnic group</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a nicely formatted table of your results using kable()</span></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>average_demographics_couty, </span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"County"</span>, <span class="st">"Total Tracts"</span>, <span class="st">"Avg White %"</span>, <span class="st">"Avg Black %"</span>, <span class="st">"Avg Hispanic %"</span>),</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a><span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a><span class="at">caption =</span> <span class="st">"Demographic Analysis of Selected County"</span></span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Demographic Analysis of Selected County</caption>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: right;">Total Tracts</th>
<th style="text-align: right;">Avg White %</th>
<th style="text-align: right;">Avg Black %</th>
<th style="text-align: right;">Avg Hispanic %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alameda</td>
<td style="text-align: right;">379</td>
<td style="text-align: right;">31.033</td>
<td style="text-align: right;">10.706</td>
<td style="text-align: right;">21.385</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alpine</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">58.086</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">14.059</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Amador</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">75.665</td>
<td style="text-align: right;">1.552</td>
<td style="text-align: right;">14.873</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="part-4-comprehensive-data-quality-evaluation" class="level1">
<h1>Part 4: Comprehensive Data Quality Evaluation</h1>
<section id="moe-analysis-for-demographic-variables" class="level2">
<h2 class="anchored" data-anchor-id="moe-analysis-for-demographic-variables">4.1 MOE Analysis for Demographic Variables</h2>
<p><strong>Your Task:</strong> Examine margins of error for demographic variables to see if some communities have less reliable data.</p>
<p><strong>Requirements:</strong> - Calculate MOE percentages for each demographic variable - Flag tracts where any demographic variable has MOE &gt; 15% - Create summary statistics</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate MOE percentages for white, Black, and Hispanic variables</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use the same formula as before (margin/estimate * 100)</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a flag for tracts with high MOE on any demographic variable</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Use logical operators (| for OR) in an ifelse() statement</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>moe_analysis <span class="ot">&lt;-</span> tract_data <span class="sc">%&gt;%</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">moe_white =</span> ((white_aloneM<span class="sc">/</span>white_aloneE)<span class="sc">*</span><span class="dv">100</span>),</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">moe_black =</span> ((blackM<span class="sc">/</span>blackE)<span class="sc">*</span><span class="dv">100</span>),</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">moe_h_l =</span> ((hispanic_latinoM<span class="sc">/</span>hispanic_latinoE)<span class="sc">*</span><span class="dv">100</span>),</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">moe_total_pop=</span>((total_popM<span class="sc">/</span>total_popE)<span class="sc">*</span><span class="dv">100</span>),</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">high_moe_flag =</span> <span class="fu">if_else</span>(</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>  (<span class="fu">is.infinite</span>(moe_white)<span class="sc">&amp;</span> moe_white <span class="sc">&gt;</span><span class="dv">15</span>)<span class="sc">|</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>  (<span class="fu">is.infinite</span>(moe_black)<span class="sc">&amp;</span> moe_black <span class="sc">&gt;</span><span class="dv">15</span>)<span class="sc">|</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>  (<span class="fu">is.infinite</span>(moe_h_l)<span class="sc">&amp;</span> moe_h_l <span class="sc">&gt;</span><span class="dv">15</span>),</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"High Uncertainty"</span>,<span class="st">"Reliable"</span></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Create summary statistics showing how many tracts have data quality issues</span></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>moe_sum<span class="ot">&lt;-</span> moe_analysis <span class="sc">%&gt;%</span></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(high_moe_flag) <span class="sc">%&gt;%</span></span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct =</span>(n<span class="sc">/</span><span class="fu">sum</span>(n))<span class="sc">*</span><span class="dv">100</span>)</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(moe_sum, <span class="at">caption =</span> <span class="st">"Summary of Tract-Level Data Quality Issues"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Summary of Tract-Level Data Quality Issues</caption>
<thead>
<tr class="header">
<th style="text-align: left;">high_moe_flag</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">pct</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">High Uncertainty</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">3.589744</td>
</tr>
<tr class="even">
<td style="text-align: left;">Reliable</td>
<td style="text-align: right;">376</td>
<td style="text-align: right;">96.410256</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="pattern-analysis" class="level2">
<h2 class="anchored" data-anchor-id="pattern-analysis">4.2 Pattern Analysis</h2>
<p><strong>Your Task:</strong> Investigate whether data quality problems are randomly distributed or concentrated in certain types of communities.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Group tracts by whether they have high MOE issues</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate average characteristics for each group:</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co"># - population size, demographic percentages</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Use group_by() and summarize() to create this comparison</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>patten_analysis <span class="ot">&lt;-</span> moe_analysis <span class="sc">%&gt;%</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_white=</span>((white_aloneE<span class="sc">/</span>total_popE)<span class="sc">*</span><span class="dv">100</span>),</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_black=</span>((blackE<span class="sc">/</span>total_popE)<span class="sc">*</span><span class="dv">100</span>),</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_h_l=</span>((hispanic_latinoE<span class="sc">/</span>total_popE)<span class="sc">*</span><span class="dv">100</span>)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>  )<span class="sc">%&gt;%</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(high_moe_flag)<span class="sc">%&gt;%</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_white=</span><span class="fu">mean</span>(pct_white, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_black=</span><span class="fu">mean</span>(pct_black, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_h_l=</span><span class="fu">mean</span>(pct_h_l, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_total=</span><span class="fu">mean</span>(total_popE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">tract_count=</span><span class="fu">n</span>()</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a professional table showing the patterns</span></span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(patten_analysis,</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Data Quality Group"</span>, <span class="st">"Avg white %"</span>, <span class="st">"Avg Black %"</span>, <span class="st">"Avg Hispanic %"</span>,<span class="st">"Avg Total Pop"</span>, <span class="st">"Tract Counts"</span>),</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a><span class="at">digits =</span> <span class="dv">2</span>,</span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a><span class="at">caption =</span> <span class="st">"Summary of Pattern Analysis"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Summary of Pattern Analysis</caption>
<colgroup>
<col style="width: 22%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 16%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Data Quality Group</th>
<th style="text-align: right;">Avg white %</th>
<th style="text-align: right;">Avg Black %</th>
<th style="text-align: right;">Avg Hispanic %</th>
<th style="text-align: right;">Avg Total Pop</th>
<th style="text-align: right;">Tract Counts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">High Uncertainty</td>
<td style="text-align: right;">48.83</td>
<td style="text-align: right;">0.83</td>
<td style="text-align: right;">12.96</td>
<td style="text-align: right;">2729.64</td>
<td style="text-align: right;">14</td>
</tr>
<tr class="even">
<td style="text-align: left;">Reliable</td>
<td style="text-align: right;">31.72</td>
<td style="text-align: right;">10.75</td>
<td style="text-align: right;">21.46</td>
<td style="text-align: right;">4435.37</td>
<td style="text-align: right;">376</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Pattern Analysis:</strong> [Describe any patterns you observe. Do certain types of communities have less reliable data? What might explain this?] Tracts with sparse populations exhibit high uncertainty due to limited sample sizes, resulting in imprecise data and a significant margin of error. In analyses, data from white populations in high-uncertainty tracts appear unreliable not because of racial issues, but because residents in sparsely populated rural areas tend to be more ethnically homogeneous than those in diverse urban centers. Consequently, higher average proportions of white residents are observed within the “high uncertainty” group.</p>
</section>
</section>
<section id="part-5-policy-recommendations" class="level1">
<h1>Part 5: Policy Recommendations</h1>
<section id="analysis-integration-and-professional-summary" class="level2">
<h2 class="anchored" data-anchor-id="analysis-integration-and-professional-summary">5.1 Analysis Integration and Professional Summary</h2>
<p><strong>Your Task:</strong> Write an executive summary that integrates findings from all four analyses.</p>
<p><strong>Executive Summary Requirements:</strong> 1. <strong>Overall Pattern Identification</strong>: What are the systematic patterns across all your analyses? 2. <strong>Equity Assessment</strong>: Which communities face the greatest risk of algorithmic bias based on your findings? 3. <strong>Root Cause Analysis</strong>: What underlying factors drive both data quality issues and bias risk? 4. <strong>Strategic Recommendations</strong>: What should the Department implement to address these systematic issues?</p>
<p><strong>Executive Summary:</strong></p>
<p>[Your integrated 4-paragraph summary here] 1. Across all four levels of analysis, a clear systematic pattern emerges: data reliability is inversely correlated with population density. At the county level, urban centers like Alameda exhibit high confidence with a margin of error (MOE) as low as 1.005%, whereas sparsely populated rural counties like Alpine suffer from low confidence with MOEs exceeding 17.2%. This trend persists at the tract level, where “High Uncertainty” areas have a significantly smaller average population (2,729) compared to “Reliable” tracts (4,435).</p>
<ol start="2" type="1">
<li><p>The communities facing the greatest risk of algorithmic bias are small, rural, and geographically isolated populations. Based on the pattern analysis, these “High Uncertainty” tracts often have a higher average percentage of White residents (48.83%) and significantly lower percentages of Black residents (0.83%) compared to urban centers. While urban minority communities benefit from the robust data of high-density areas, rural residents—regardless of race—are at risk of being “miscalculated” by algorithms that do not account for the high statistical noise inherent in small-sample data.</p></li>
<li><p>The primary driver of this bias risk is the inherent limitation of sampling in low-density areas. In a county like Alpine, which has a total population of only 1,515, the American Community Survey (ACS) sample size is so small that a few outlier responses can drastically skew the median income estimate. Algorithms treat these estimates as absolute facts, but in reality, they are “statistical flukes” caused by the geographic reality of rural life, creating a structural bias where data-rich urban areas receive more predictable and “fair” algorithmic treatment than data-sparse rural ones.</p></li>
<li><p>To mitigate these risks, the Department of Human Services should implement a “Reliability-Aware” Decision Framework. First, any community flagged with an MOE &gt; 10% should be diverted from fully automated processing to a manual administrative review. Second, the Department should supplement Census data with local administrative records (such as state tax or utility data) for rural tracts to triangulate income estimates.</p></li>
</ol>
</section>
<section id="specific-recommendations" class="level2">
<h2 class="anchored" data-anchor-id="specific-recommendations">6.3 Specific Recommendations</h2>
<p><strong>Your Task:</strong> Create a decision framework for algorithm implementation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a summary table using your county reliability data</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Include: county name, median income, MOE percentage, reliability category</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a new column with algorithm recommendations using case_when():</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="co"># - High Confidence: "Safe for algorithmic decisions"</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="co"># - Moderate Confidence: "Use with caution - monitor outcomes"  </span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co"># - Low Confidence: "Requires manual review or additional data"</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>decision_framework <span class="ot">&lt;-</span> income_analysis <span class="sc">%&gt;%</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>( NAME, med_incomeE, moe_pct,total_popE,reliability,) <span class="sc">%&gt;%</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">algo_recommendation =</span> <span class="fu">case_when</span>(</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>      reliability <span class="sc">==</span> <span class="st">"High Confidence"</span><span class="sc">~</span><span class="st">"Safe for algorithmic decisions"</span>,</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>      reliability <span class="sc">==</span> <span class="st">"Moderate Confidence"</span><span class="sc">~</span><span class="st">"Use with caution - monitor outcomes"</span>,</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>      reliability <span class="sc">==</span> <span class="st">"Low Confidence"</span><span class="sc">~</span><span class="st">"Requires manual review or additional data"</span></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Format as a professional table with kable()</span></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(decision_framework,</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"county name"</span>, <span class="st">"median income"</span>, <span class="st">"MOE percentage"</span>, <span class="st">"Total population"</span>,<span class="st">"Reliability"</span>,<span class="st">"Policy Recommendation"</span>),</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a><span class="at">digits =</span> <span class="dv">2</span>,</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a><span class="at">caption =</span> <span class="st">"Decision Framework for Algorithm Implementation"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Decision Framework for Algorithm Implementation</caption>
<colgroup>
<col style="width: 12%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 16%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">county name</th>
<th style="text-align: right;">median income</th>
<th style="text-align: right;">MOE percentage</th>
<th style="text-align: right;">Total population</th>
<th style="text-align: left;">Reliability</th>
<th style="text-align: left;">Policy Recommendation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alameda</td>
<td style="text-align: right;">122488</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1663823</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alpine</td>
<td style="text-align: right;">101125</td>
<td style="text-align: right;">17.25</td>
<td style="text-align: right;">1515</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Amador</td>
<td style="text-align: right;">74853</td>
<td style="text-align: right;">8.08</td>
<td style="text-align: right;">40577</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Butte</td>
<td style="text-align: right;">66085</td>
<td style="text-align: right;">3.42</td>
<td style="text-align: right;">213605</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Calaveras</td>
<td style="text-align: right;">77526</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">45674</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Colusa</td>
<td style="text-align: right;">69619</td>
<td style="text-align: right;">8.25</td>
<td style="text-align: right;">21811</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Contra Costa</td>
<td style="text-align: right;">120020</td>
<td style="text-align: right;">1.25</td>
<td style="text-align: right;">1162648</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Del Norte</td>
<td style="text-align: right;">61149</td>
<td style="text-align: right;">7.16</td>
<td style="text-align: right;">27462</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">El Dorado</td>
<td style="text-align: right;">99246</td>
<td style="text-align: right;">3.36</td>
<td style="text-align: right;">191713</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fresno</td>
<td style="text-align: right;">67756</td>
<td style="text-align: right;">1.43</td>
<td style="text-align: right;">1008280</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Glenn</td>
<td style="text-align: right;">64033</td>
<td style="text-align: right;">6.19</td>
<td style="text-align: right;">28657</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Humboldt</td>
<td style="text-align: right;">57881</td>
<td style="text-align: right;">3.68</td>
<td style="text-align: right;">136132</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Imperial</td>
<td style="text-align: right;">53847</td>
<td style="text-align: right;">4.11</td>
<td style="text-align: right;">179578</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Inyo</td>
<td style="text-align: right;">63417</td>
<td style="text-align: right;">8.60</td>
<td style="text-align: right;">18829</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kern</td>
<td style="text-align: right;">63883</td>
<td style="text-align: right;">2.07</td>
<td style="text-align: right;">906883</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kings</td>
<td style="text-align: right;">68540</td>
<td style="text-align: right;">3.29</td>
<td style="text-align: right;">152515</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lake</td>
<td style="text-align: right;">56259</td>
<td style="text-align: right;">4.34</td>
<td style="text-align: right;">68024</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lassen</td>
<td style="text-align: right;">59515</td>
<td style="text-align: right;">5.97</td>
<td style="text-align: right;">31873</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Los Angeles</td>
<td style="text-align: right;">83411</td>
<td style="text-align: right;">0.53</td>
<td style="text-align: right;">9936690</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Madera</td>
<td style="text-align: right;">73543</td>
<td style="text-align: right;">3.87</td>
<td style="text-align: right;">157243</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Marin</td>
<td style="text-align: right;">142019</td>
<td style="text-align: right;">2.89</td>
<td style="text-align: right;">260485</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mariposa</td>
<td style="text-align: right;">60021</td>
<td style="text-align: right;">8.82</td>
<td style="text-align: right;">17130</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mendocino</td>
<td style="text-align: right;">61335</td>
<td style="text-align: right;">3.58</td>
<td style="text-align: right;">91145</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Merced</td>
<td style="text-align: right;">64772</td>
<td style="text-align: right;">3.31</td>
<td style="text-align: right;">282290</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Modoc</td>
<td style="text-align: right;">54962</td>
<td style="text-align: right;">9.80</td>
<td style="text-align: right;">8651</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mono</td>
<td style="text-align: right;">82038</td>
<td style="text-align: right;">18.76</td>
<td style="text-align: right;">13219</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Monterey</td>
<td style="text-align: right;">91043</td>
<td style="text-align: right;">2.09</td>
<td style="text-align: right;">437609</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Napa</td>
<td style="text-align: right;">105809</td>
<td style="text-align: right;">2.82</td>
<td style="text-align: right;">137384</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nevada</td>
<td style="text-align: right;">79395</td>
<td style="text-align: right;">4.82</td>
<td style="text-align: right;">102322</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Orange</td>
<td style="text-align: right;">109361</td>
<td style="text-align: right;">0.81</td>
<td style="text-align: right;">3175227</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Placer</td>
<td style="text-align: right;">109375</td>
<td style="text-align: right;">1.70</td>
<td style="text-align: right;">406608</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Plumas</td>
<td style="text-align: right;">67885</td>
<td style="text-align: right;">11.45</td>
<td style="text-align: right;">19650</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Riverside</td>
<td style="text-align: right;">84505</td>
<td style="text-align: right;">1.26</td>
<td style="text-align: right;">2429487</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sacramento</td>
<td style="text-align: right;">84010</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">1579211</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">San Benito</td>
<td style="text-align: right;">104451</td>
<td style="text-align: right;">5.23</td>
<td style="text-align: right;">64753</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">San Bernardino</td>
<td style="text-align: right;">77423</td>
<td style="text-align: right;">1.04</td>
<td style="text-align: right;">2180563</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">San Diego</td>
<td style="text-align: right;">96974</td>
<td style="text-align: right;">1.02</td>
<td style="text-align: right;">3289701</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">San Francisco</td>
<td style="text-align: right;">136689</td>
<td style="text-align: right;">1.43</td>
<td style="text-align: right;">851036</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">San Joaquin</td>
<td style="text-align: right;">82837</td>
<td style="text-align: right;">1.75</td>
<td style="text-align: right;">779445</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">San Luis Obispo</td>
<td style="text-align: right;">90158</td>
<td style="text-align: right;">2.56</td>
<td style="text-align: right;">281712</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">San Mateo</td>
<td style="text-align: right;">149907</td>
<td style="text-align: right;">1.75</td>
<td style="text-align: right;">754250</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Santa Barbara</td>
<td style="text-align: right;">92332</td>
<td style="text-align: right;">2.05</td>
<td style="text-align: right;">445213</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Santa Clara</td>
<td style="text-align: right;">153792</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1916831</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Santa Cruz</td>
<td style="text-align: right;">104409</td>
<td style="text-align: right;">3.04</td>
<td style="text-align: right;">268571</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Shasta</td>
<td style="text-align: right;">68347</td>
<td style="text-align: right;">3.63</td>
<td style="text-align: right;">181852</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sierra</td>
<td style="text-align: right;">61108</td>
<td style="text-align: right;">15.12</td>
<td style="text-align: right;">2916</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Siskiyou</td>
<td style="text-align: right;">53898</td>
<td style="text-align: right;">4.90</td>
<td style="text-align: right;">44049</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Solano</td>
<td style="text-align: right;">97037</td>
<td style="text-align: right;">1.78</td>
<td style="text-align: right;">450995</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sonoma</td>
<td style="text-align: right;">99266</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">488436</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Stanislaus</td>
<td style="text-align: right;">74872</td>
<td style="text-align: right;">1.83</td>
<td style="text-align: right;">552063</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sutter</td>
<td style="text-align: right;">72654</td>
<td style="text-align: right;">4.71</td>
<td style="text-align: right;">99101</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tehama</td>
<td style="text-align: right;">59029</td>
<td style="text-align: right;">6.95</td>
<td style="text-align: right;">65484</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Trinity</td>
<td style="text-align: right;">47317</td>
<td style="text-align: right;">12.45</td>
<td style="text-align: right;">15889</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tulare</td>
<td style="text-align: right;">64474</td>
<td style="text-align: right;">2.31</td>
<td style="text-align: right;">473446</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tuolumne</td>
<td style="text-align: right;">70432</td>
<td style="text-align: right;">6.66</td>
<td style="text-align: right;">54993</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ventura</td>
<td style="text-align: right;">102141</td>
<td style="text-align: right;">1.50</td>
<td style="text-align: right;">842009</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Yolo</td>
<td style="text-align: right;">85097</td>
<td style="text-align: right;">2.74</td>
<td style="text-align: right;">217141</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yuba</td>
<td style="text-align: right;">66693</td>
<td style="text-align: right;">4.19</td>
<td style="text-align: right;">81705</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Key Recommendations:</strong></p>
<p><strong>Your Task:</strong> Use your analysis results to provide specific guidance to the department.</p>
<ol type="1">
<li><p><strong>Counties suitable for immediate algorithmic implementation:</strong> [List counties with high confidence data and explain why they’re appropriate] Alameda Butte Calaveras Contra Costa El Dorado Fresno Humboldt Imperial Kern Kings Lake Los Angeles Madera Marin Mendocino Merced Monterey Napa Nevada Orange Placer Riverside Sacramento San Bernardino San Diego San Francisco San Joaquin San Luis Obispo San Mateo Santa Barbara Santa Clara Santa Cruz Shasta Siskiyou Solano Sonoma Stanislaus Sutter Tulare Ventura Yolo Yuba These counties have large populations and exceptionally large sample sizes, resulting in an extremely low margin of error (MOE) of approximately 1%. Their income estimates are highly stable, and the risk of algorithmic bias in these areas is minimal, making them safe for automated funding allocation.</p></li>
<li><p><strong>Counties requiring additional oversight:</strong> [List counties with moderate confidence data and describe what kind of monitoring would be needed] Amador Colusa Del Norte Glenn Inyo Lassen Mariposa Modoc San Benito Tehama Tuolumne Although the data is generally accurate, it exhibits a certain degree of volatility. It is recommended that while implementing the algorithm, an output monitoring mechanism be established to periodically conduct random sampling and inspection of anomalous allocation cases, ensuring the algorithm does not develop bias due to data fluctuations.</p></li>
<li><p><strong>Counties needing alternative approaches:</strong> [List counties with low confidence data and suggest specific alternatives - manual review, additional surveys, etc.] Alpine Mono Plumas Sierra Trinity These counties have sparse populations, resulting in extremely unstable data with errors exceeding 17%. Direct application of algorithms would lead to severe geographic inequities. A “manual verification” mechanism could be implemented for these counties, or supplementary investigations could be conducted using state government administrative records to compensate for the shortcomings of census sample data.</p></li>
</ol>
</section>
<section id="questions-for-further-investigation" class="level2">
<h2 class="anchored" data-anchor-id="questions-for-further-investigation">Questions for Further Investigation</h2>
<p>[List 2-3 questions that your analysis raised that you’d like to explore further in future assignments. Consider questions about spatial patterns, time trends, or other demographic factors.] 1.Has the reliability of data for these remote counties improved or deteriorated over the past decade as the Census Bureau updated its sampling methods? 2.Could incorporating “income” alongside other metrics help reduce bias in the final results? # Technical Notes</p>
<p><strong>Data Sources:</strong> - U.S. Census Bureau, American Community Survey 2018-2022 5-Year Estimates - Retrieved via tidycensus R package on February 9, 2026.</p>
<p><strong>Reproducibility:</strong> - All analysis conducted in R version 4.3.0 - Census API key required for replication - Complete code and documentation available at: [your portfolio URL]</p>
<p><strong>Methodology Notes:</strong> County and tract names were cleaned using regular expressions to remove repetitive legal suffixes (e.g., “; California”), ensuring the final visualizations and tables were policy-ready.</p>
<p><strong>Limitations:</strong> The focus was restricted to California (CA); findings regarding rural data uncertainty may vary in states with different administrative structures or population distributions.</p>
<hr>
</section>
<section id="submission-checklist" class="level2">
<h2 class="anchored" data-anchor-id="submission-checklist">Submission Checklist</h2>
<p>Before submitting your portfolio link on Canvas:</p>
<ul class="task-list">
<li><label><input type="checkbox">All code chunks run without errors</label></li>
<li><label><input type="checkbox">All “[Fill this in]” prompts have been completed</label></li>
<li><label><input type="checkbox">Tables are properly formatted and readable</label></li>
<li><label><input type="checkbox">Executive summary addresses all four required components</label></li>
<li><label><input type="checkbox">Portfolio navigation includes this assignment</label></li>
<li><label><input type="checkbox">Census API key is properly set</label></li>
<li><label><input type="checkbox">Document renders correctly to HTML</label></li>
</ul>
<p><strong>Remember:</strong> Submit your portfolio URL on Canvas, not the file itself. Your assignment should be accessible at <code>your-portfolio-url/labs/lab_1/your_file_name.html</code></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>